Rails.application.config.assets.precompile += %w( html5.js )
Rails.application.config.assets.precompile += %w( market.css )
Rails.application.config.assets.precompile += %w( market.js )
Rails.application.config.assets.precompile += %w( charting_library/charting_library.min.js )
Rails.application.config.assets.precompile += %w( datafeeds/udf/bundle.js )
Rails.application.config.assets.precompile += %w( datafeeds/udf/polyfills.js )
